### PR TITLE
Use proper types for most things

### PR DESCRIPTION
**Pull request by miekg**
This change introduces type for most (not all yet) things you can do the zammad API, such as: User, Group, Ticket, etc. This makes it easier to use the exported API.

Some fields are `any` because the documentation is very unclear on what type the field should have.

### CODE REVIEW

**Comment by miekg** [comment]
note the diff is huge because every file went through a dos2unix

**Comment by AlessandroSechi** [comment]
Thank you!

**Comment by miekg** [comment]
Cheers!

I'll continue to post PRs for other things, looking at tags.go right now, seems tickets_tags.go is also a good new candidate.

Do you care about backwards incompatible changes? E.g. I want to change client.Url into client.URL to be more inline with Go guidelines for naming things.

**Comment by AlessandroSechi** [comment]
> Do you care about backwards incompatible changes?

No. I think at some point, once lib is more mature, I can tag major version and then care about backwards incompatible changes from that moment

**Pull request merged**
